// frontend/src/views/ai-assistant/NodeContent.vue
<template>
  <div class="node-content">
    <!-- Intent Section (Top) -->
    <div class="intent-section">
      <div class="section-header">
        <div class="header-left">
          <h3 class="section-title">意图澄清</h3>
          <span class="status-badge" :class="statusClass">
            {{ statusText }}
          </span>
        </div>
      </div>
      <div class="section-body">
        <dynamic-form
          ref="intentFormRef"
          :schema="intentSchema"
          v-model="intentFormData"
          :readonly="isNodeExecuted"
        />
      </div>
      <div v-if="!isNodeExecuted && !isLoading" class="action-bar">
        <el-button @click="handleReset" class="btn-reset">重置</el-button>
        <el-button type="primary" @click="handleExecute" class="btn-primary">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M13 5l7 7-7 7M5 12h15"/>
          </svg>
          执行工作流
        </el-button>
      </div>
      <div v-if="isLoading" class="action-bar">
        <el-button type="warning" @click="handleMockComplete" class="btn-mock">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M22 11.08V12a10 10 0 11-5.93-9.14"/>
            <polyline points="22 4 12 14.01 9 11.01"/>
          </svg>
          Mock 完成
        </el-button>
      </div>
    </div>

    <!-- Divider with badge -->
    <div v-if="hasArtifact" class="divider">
      <div class="divider-line"></div>
      <span class="divider-badge">数据输出</span>
      <div class="divider-line"></div>
    </div>

    <!-- Artifact Section (Bottom) -->
    <div v-if="hasArtifact" class="artifact-section">
      <div class="section-header">
        <div class="header-left">
          <h3 class="section-title">生成物展示</h3>
        </div>
      </div>
      <div class="section-body">
        <dynamic-form
          :schema="artifactSchema"
          :model-value="artifactFormData"
          readonly
        />
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="isLoading" class="loading-state">
      <div class="loading-ring"></div>
      <p>执行中...</p>
    </div>

    <!-- Empty State -->
    <div v-if="!hasArtifact && !isLoading && isNodeExecuted" class="empty-state">
      <p>暂无生成物数据</p>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { useTaskStore } from '@/store/task'
import DynamicForm from './DynamicForm.vue'

const taskStore = useTaskStore()

const intentFormRef = ref(null)
const intentFormData = ref({})
const artifactFormData = ref({})

// Computed: check if node is executed
const isNodeExecuted = computed(() => {
  const node = taskStore.currentNode
  if (!node) return false
  return node.status === 'completed' || node.status === 'running'
})

// Computed: check if node has artifact data
const hasArtifact = computed(() => {
  const node = taskStore.currentNode
  if (!node || !node.artifact_data) return false
  return Object.keys(node.artifact_data).length > 0
})

// Computed: status text
const statusText = computed(() => {
  const node = taskStore.currentNode
  if (!node) return '未知'
  const statusMap = {
    pending: '待执行',
    running: '执行中',
    completed: '已完成',
    failed: '失败'
  }
  return statusMap[node.status] || node.status
})

// Computed: status class
const statusClass = computed(() => {
  const node = taskStore.currentNode
  if (!node) return ''
  return `status-${node.status}`
})

// Computed: loading state
const isLoading = computed(() => {
  const node = taskStore.currentNode
  return node && node.status === 'running'
})

// Computed: load intent schema from node
const intentSchema = computed(() => {
  const node = taskStore.currentNode
  if (!node || !node.intent_schema) return null
  return node.intent_schema
})

// Computed: load artifact schema from node
const artifactSchema = computed(() => {
  const node = taskStore.currentNode
  if (!node || !node.artifact_schema) return null
  return node.artifact_schema
})

// Watch artifact data changes
watch(
  () => taskStore.currentNode?.artifact_data,
  (data) => {
    if (data) {
      artifactFormData.value = { ...data }
    }
  },
  { immediate: true, deep: true }
)

// Watch intent data changes (to load saved form data)
watch(
  () => taskStore.currentTask?.node_executions,
  (executions) => {
    if (executions && taskStore.currentNodeId) {
      const node = executions.find(n => n.node_id === taskStore.currentNodeId)
      if (node && node.intent_data) {
        intentFormData.value = { ...node.intent_data }
      }
    }
  },
  { immediate: true, deep: true }
)

// Also watch currentNodeId changes
watch(
  () => taskStore.currentNodeId,
  () => {
    const node = taskStore.currentNode
    if (node && node.intent_data) {
      intentFormData.value = { ...node.intent_data }
    }
  }
)

// Handle reset
const handleReset = () => {
  intentFormData.value = {}
}

// Handle execute
const handleExecute = async () => {
  const node = taskStore.currentNode
  if (!node) return

  await taskStore.executeNode(node.node_id, intentFormData.value)
}

// Handle mock complete for testing
const handleMockComplete = async () => {
  const node = taskStore.currentNode
  if (!node) return

  await taskStore.mockCompleteNode(node.node_id)
}
</script>

<style scoped>
.node-content {
  display: flex;
  flex-direction: column;
  gap: 20px;
  padding: 20px;
  font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, sans-serif;
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.04) 0%, rgba(118, 75, 162, 0.04) 100%);
  border-radius: 12px 12px 0 0;
  border: 1px solid rgba(0, 0, 0, 0.04);
  border-bottom: none;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 12px;
}

.section-title {
  font-size: 0.95rem;
  font-weight: 600;
  color: #1a1a2e;
  margin: 0;
}

.status-badge {
  padding: 4px 10px;
  border-radius: 20px;
  font-size: 0.75rem;
  font-weight: 600;
}

.status-badge.status-pending {
  background: rgba(100, 116, 139, 0.1);
  color: #64748b;
}

.status-badge.status-running {
  background: rgba(102, 126, 234, 0.1);
  color: #667eea;
}

.status-badge.status-completed {
  background: rgba(16, 185, 129, 0.1);
  color: #10B981;
}

.status-badge.status-failed {
  background: rgba(239, 68, 68, 0.1);
  color: #EF4444;
}

.section-body {
  padding: 20px;
  background: #fff;
  border: 1px solid rgba(0, 0, 0, 0.04);
  border-radius: 0 0 12px 12px;
  border-top: none;
}

/* Intent section card styling */
.intent-section {
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.04);
  border: 1px solid rgba(0, 0, 0, 0.04);
  overflow: hidden;
}

/* Action bar */
.action-bar {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding: 16px 20px;
  background: #fafafa;
  border-top: 1px solid rgba(0, 0, 0, 0.04);
}

.btn-reset {
  padding: 10px 20px;
  border-radius: 10px;
  border: 1px solid rgba(0, 0, 0, 0.08);
  background: #fff;
  color: #64748b;
  font-weight: 500;
  transition: all 0.2s;
}

.btn-reset:hover {
  border-color: #667eea;
  color: #667eea;
}

.btn-primary {
  padding: 10px 24px;
  border-radius: 10px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border: none;
  color: #fff;
  font-weight: 600;
  display: flex;
  align-items: center;
  gap: 8px;
  transition: all 0.2s;
}

.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(102, 126, 234, 0.35);
}

/* Divider */
.divider {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 0 20px;
}

.divider-line {
  flex: 1;
  height: 1px;
  background: linear-gradient(90deg, transparent 0%, rgba(102, 126, 234, 0.3) 50%, transparent 100%);
}

.divider-badge {
  padding: 6px 14px;
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%);
  border-radius: 20px;
  font-size: 0.75rem;
  font-weight: 600;
  color: #667eea;
}

/* Artifact section card styling */
.artifact-section {
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.04);
  border: 1px solid rgba(0, 0, 0, 0.04);
  overflow: hidden;
  flex: 1;
  display: flex;
  flex-direction: column;
}

/* Loading state */
.loading-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.04);
  border: 1px solid rgba(0, 0, 0, 0.04);
}

.loading-ring {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  border: 3px solid transparent;
  border-top-color: #667eea;
  animation: spin 1s linear infinite;
  margin-bottom: 16px;
}

.loading-ring::before {
  content: '';
  position: absolute;
  inset: 4px;
  border-radius: 50%;
  border: 3px solid transparent;
  border-top-color: #764ba2;
  animation: spin 0.8s linear infinite reverse;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.loading-state p {
  margin: 0;
  font-size: 0.85rem;
  color: #64748b;
}

/* Empty state */
.empty-state {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.04);
  border: 1px solid rgba(0, 0, 0, 0.04);
}

.empty-state p {
  margin: 0;
  font-size: 0.85rem;
  color: #94a3b8;
}

/* Form readonly state - gray background */
:deep(.section-body:has(.dynamic-form[readonly])) {
  background: #f8f9fb;
}
</style>

// frontend-react/src/pages/ai-assistant/NodeContent.jsx
import { useState, useEffect, useMemo } from 'react'
import { Button } from 'antd'
import { useTaskStore } from '@/store/task'
import AmISForm from './AmISForm'

function NodeContent() {
  const currentTask = useTaskStore(s => s.currentTask)
  const currentNodeId = useTaskStore(s => s.currentNodeId)
  const isExecuting = useTaskStore(s => s.isExecuting)
  const executeNode = useTaskStore(s => s.executeNode)
  const mockCompleteNode = useTaskStore(s => s.mockCompleteNode)

  const [intentData, setIntentData] = useState({})
  const [artifactData, setArtifactData] = useState({})

  const currentNode = useMemo(() => {
    return currentTask?.node_executions?.find(n => n.node_id === currentNodeId)
  }, [currentTask?.node_executions, currentNodeId])

  useEffect(() => {
    if (currentNode?.intent_data) {
      setIntentData(currentNode.intent_data)
    }
  }, [currentNode?.intent_data])

  useEffect(() => {
    if (currentNode?.artifact_data) {
      setArtifactData(currentNode.artifact_data)
    }
  }, [currentNode?.artifact_data])

  const statusMap = {
    pending: { text: '待执行', color: '#86909C', bg: '#F5F7FA' },
    running: { text: '执行中', color: '#FF8C00', bg: '#FFF4E6' },
    completed: { text: '已完成', color: '#52C41A', bg: '#F6FFED' },
    failed: { text: '失败', color: '#FF4D4F', bg: '#FFF2F0' }
  }

  const isRunning = currentNode?.status === 'running'
  const isPending = currentNode?.status === 'pending'
  const isCompleted = currentNode?.status === 'completed'
  const isFailed = currentNode?.status === 'failed'
  const isNodeRunning = isRunning || isExecuting
  const isExecuted = isCompleted || isFailed

  console.log('[NodeContent] Node state:', {
    status: currentNode?.status,
    isRunning,
    isNodeRunning,
    isExecuting,
    isExecuted
  })
  const hasArtifact = currentNode?.artifact_data && Object.keys(currentNode.artifact_data).length > 0
  const hasArtifactSchema = !!currentNode?.artifact_schema

  const handleExecute = async () => {
    await executeNode(currentNodeId, intentData)
  }

  const handleMockComplete = async () => {
    await mockCompleteNode(currentNodeId)
  }

  const status = statusMap[currentNode?.status] || statusMap.pending

  // 执行中状态的旋转动画 SVG
  const SpinnerIcon = () => (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ animation: 'spin 1s linear infinite' }}>
      <path d="M21 12a9 9 0 11-6.219-8.56" />
    </svg>
  )

  return (
    <div style={{
      padding: 20,
      overflow: 'auto',
      flex: 1,
      background: '#F5F7FA'
    }}>
      {/* Intent Section */}
      <div style={{
        background: '#FFFFFF',
        borderRadius: 12,
        border: '1px solid #E5E6EB',
        marginBottom: 20,
        overflow: 'hidden'
      }}>
        <div style={{
          padding: '16px 20px',
          background: '#FAFAFA',
          borderBottom: '1px solid #E5E6EB',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <span style={{ fontWeight: 600, fontSize: '14px', color: '#1D2129' }}>意图澄清</span>
            <span style={{
              fontSize: '11px',
              color: '#5C7CFF',
              background: '#F0F1FF',
              padding: '2px 8px',
              borderRadius: 4
            }}>
              输入
            </span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            {(isExecuting || isRunning) && (
              <span style={{
                display: 'flex',
                alignItems: 'center',
                gap: 6,
                fontSize: '12px',
                color: '#FF8C00',
                fontWeight: 500
              }}>
                <SpinnerIcon />
                执行中...
              </span>
            )}
            <span style={{
              fontSize: '12px',
              color: status.color,
              background: status.bg,
              padding: '4px 12px',
              borderRadius: 20
            }}>
              {status.text}
            </span>
          </div>
        </div>
        <div style={{ padding: 20 }}>
          <AmISForm
            schema={currentNode?.intent_schema}
            value={intentData}
            onChange={setIntentData}
            readonly={isExecuted}
          />
        </div>
        {!isExecuted && !isExecuting && (
          <div style={{
            padding: '16px 20px',
            background: '#FAFAFA',
            borderTop: '1px solid #E5E6EB',
            display: 'flex',
            justifyContent: 'flex-end',
            gap: 12
          }}>
            <Button style={{ borderRadius: 8 }}>重置</Button>
            <Button
              type="primary"
              onClick={handleExecute}
              style={{
                borderRadius: 8,
                background: '#5C7CFF',
                border: 'none'
              }}
            >
              执行工作流
            </Button>
          </div>
        )}
        {(isExecuting || isRunning) && (
          <div style={{
            padding: '16px 20px',
            background: '#FAFAFA',
            borderTop: '1px solid #E5E6EB',
            display: 'flex',
            justifyContent: 'flex-end'
          }}>
            <Button
              type="primary"
              onClick={handleMockComplete}
              style={{ borderRadius: 8, background: '#5C7CFF', border: 'none' }}
            >
              Mock 完成
            </Button>
          </div>
        )}
      </div>

      {/* Artifact Section */}
      {(hasArtifactSchema || hasArtifact) && (
        <>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: 16,
            marginBottom: 16
          }}>
            <div style={{ flex: 1, height: 1, background: '#E5E6EB' }} />
            <span style={{
              padding: '6px 14px',
              background: '#F0F1FF',
              borderRadius: 20,
              fontSize: '12px',
              fontWeight: 600,
              color: '#5C7CFF'
            }}>
              数据输出
            </span>
            <div style={{ flex: 1, height: 1, background: '#E5E6EB' }} />
          </div>
          <div style={{
            background: '#FFFFFF',
            borderRadius: 12,
            border: '1px solid #E5E6EB',
            overflow: 'hidden'
          }}>
            <div style={{
              padding: '16px 20px',
              background: '#FAFAFA',
              borderBottom: '1px solid #E5E6EB',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center'
            }}>
              <span style={{ fontWeight: 600, fontSize: '14px', color: '#1D2129' }}>生成物展示</span>
              <span style={{
                fontSize: '11px',
                color: '#52C41A',
                background: '#F6FFED',
                padding: '2px 8px',
                borderRadius: 4
              }}>
                输出
              </span>
            </div>

            {/* Loading State - 显示在生成物区域内部 */}
            {isNodeRunning && (
              <div style={{
                padding: 60,
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center'
              }}>
                {/* Animated arc icon */}
                <div style={{
                  width: 48,
                  height: 48,
                  borderRadius: '50%',
                  border: '3px solid #F0F1FF',
                  borderTopColor: '#667eea',
                  animation: 'spin 1s linear infinite',
                  marginBottom: 20,
                  position: 'relative'
                }}>
                  <div style={{
                    position: 'absolute',
                    inset: 4,
                    borderRadius: '50%',
                    border: '3px solid #F0F1FF',
                    borderTopColor: '#764ba2',
                    animation: 'spin 0.8s linear infinite reverse'
                  }} />
                </div>

                <p style={{
                  fontSize: '14px',
                  color: '#1D2129',
                  fontWeight: 500,
                  marginBottom: 8,
                  margin: 0
                }}>
                  节点数据查询中，请稍候...
                </p>

                {/* Progress bar */}
                <div style={{
                  width: 240,
                  height: 4,
                  background: '#F0F1FF',
                  borderRadius: 2,
                  overflow: 'hidden',
                  marginBottom: 12
                }}>
                  <div style={{
                    height: '100%',
                    width: '60%',
                    background: 'linear-gradient(90deg, #667eea 0%, #764ba2 100%)',
                    borderRadius: 2,
                    animation: 'progress 2s ease-in-out infinite'
                  }} />
                </div>

                <p style={{
                  fontSize: '12px',
                  color: '#86909C',
                  margin: 0
                }}>
                  正在从数据源获取数据...
                </p>
              </div>
            )}

            {/* Artifact Form */}
            {!isNodeRunning && hasArtifact && artifactData && Object.keys(artifactData).length > 0 && (
              <div style={{ padding: 20 }}>
                <AmISForm
                  schema={currentNode?.artifact_schema}
                  value={artifactData}
                  readonly
                />
              </div>
            )}

            {/* Empty state when no artifact */}
            {!isNodeRunning && !hasArtifact && hasArtifactSchema && (
              <div style={{
                padding: 40,
                textAlign: 'center',
                color: '#86909C',
                fontSize: '13px'
              }}>
                暂无生成物数据
              </div>
            )}
          </div>
        </>
      )}
      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
        @keyframes progress {
          0% { width: 0%; opacity: 0.5; }
          50% { width: 100%; opacity: 1; }
          100% { width: 0%; opacity: 0.5; }
        }
      `}</style>
    </div>
  )
}

export default NodeContent
