// frontend/src/views/workflow-config/index.vue
<template>
  <div class="workflow-config">
    <el-tabs v-model="activeTab">
      <el-tab-pane label="N8N环境" name="environments">
        <environment-list />
      </el-tab-pane>
      <el-tab-pane label="工作流路由" name="routes">
        <workflow-routes />
      </el-tab-pane>
      <el-tab-pane label="节点映射" name="mappings">
        <node-mappings />
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import EnvironmentList from './EnvironmentList.vue'
import WorkflowRoutes from './WorkflowRoutes.vue'
import NodeMappings from './NodeMappings.vue'

const activeTab = ref('environments')
</script>

<style scoped>
.workflow-config {
  background: #fff;
  border-radius: 8px;
  padding: 20px;
}
</style>

// frontend-react/src/pages/workflow-config/index.jsx
import { Tabs } from 'antd'
import EnvironmentList from './EnvironmentList'
import WorkflowRoutes from './WorkflowRoutes'
import NodeMappings from './NodeMappings'

function WorkflowConfig() {
  const items = [
    { key: 'environments', label: '环境配置', children: <EnvironmentList /> },
    { key: 'routes', label: '工作流路由', children: <WorkflowRoutes /> },
    { key: 'mappings', label: '节点映射', children: <NodeMappings /> }
  ]

  return (
    <div style={{ padding: 24, background: '#F5F7FA', minHeight: '100%' }}>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: 24, color: '#1D2129' }}>工作流配置</h1>
      <Tabs items={items} />
    </div>
  )
}

export default WorkflowConfig
