// frontend/src/views/workflow-config/NodeMappings.vue
<template>
  <div class="node-mappings">
    <div class="toolbar">
      <el-select v-model="selectedRouteId" placeholder="选择工作流" @change="fetchMappings">
        <el-option
          v-for="wf in workflows"
          :key="wf.id"
          :label="wf.title"
          :value="wf.id"
        />
      </el-select>
      <el-button type="primary" @click="handleCreate" :disabled="!selectedRouteId">
        <el-icon><Plus /></el-icon>
        新建映射
      </el-button>
    </div>

    <el-table :data="mappings" v-loading="loading">
      <el-table-column prop="node_id" label="节点ID" />
      <el-table-column prop="node_name" label="节点名称" />
      <el-table-column prop="intent_schema_path" label="意图表单路径" show-overflow-tooltip />
      <el-table-column prop="artifact_schema_path" label="生成物表单路径" show-overflow-tooltip />
      <el-table-column label="操作" width="150">
        <template #default="{ row }">
          <el-button link type="primary" @click="handleEdit(row)">编辑</el-button>
          <el-button link type="danger" @click="handleDelete(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog v-model="dialogVisible" :title="dialogTitle" width="600px">
      <el-form :model="formData" label-width="140px">
        <el-form-item label="节点ID">
          <el-input v-model="formData.node_id" />
        </el-form-item>
        <el-form-item label="节点名称">
          <el-input v-model="formData.node_name" />
        </el-form-item>
        <el-form-item label="意图表单Schema路径">
          <el-input v-model="formData.intent_schema_path" placeholder="intent_forms/{route_id}/intent_schema.json" />
        </el-form-item>
        <el-form-item label="生成物表单Schema路径">
          <el-input v-model="formData.artifact_schema_path" placeholder="artifact_forms/{route_id}/artifact_schema.json" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSave">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import { workflowApi } from '@/api/workflow'

const workflows = ref([])
const mappings = ref([])
const selectedRouteId = ref(null)
const loading = ref(false)
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formData = ref({
  node_id: '',
  node_name: '',
  intent_schema_path: '',
  artifact_schema_path: ''
})

onMounted(() => {
  fetchWorkflows()
})

const fetchWorkflows = async () => {
  const res = await workflowApi.getWorkflows()
  workflows.value = res.data.items
}

const fetchMappings = async () => {
  if (!selectedRouteId.value) return
  loading.value = true
  try {
    const res = await workflowApi.getMappings(selectedRouteId.value)
    mappings.value = res.data.items
  } finally {
    loading.value = false
  }
}

const handleCreate = () => {
  formData.value = { node_id: '', node_name: '', intent_schema_path: '', artifact_schema_path: '' }
  dialogTitle.value = '新建映射'
  dialogVisible.value = true
}

const handleEdit = (row) => {
  formData.value = { ...row }
  dialogTitle.value = '编辑映射'
  dialogVisible.value = true
}

const handleSave = async () => {
  try {
    if (formData.value.id) {
      await workflowApi.updateMapping(formData.value.id, formData.value)
      ElMessage.success('更新成功')
    } else {
      await workflowApi.createMapping(selectedRouteId.value, formData.value)
      ElMessage.success('创建成功')
    }
    dialogVisible.value = false
    fetchMappings()
  } catch (e) {
    ElMessage.error('操作失败')
  }
}

const handleDelete = async (row) => {
  try {
    await ElMessageBox.confirm('确认删除该映射吗？', '警告', { type: 'warning' })
    await workflowApi.deleteMapping(row.id)
    ElMessage.success('删除成功')
    fetchMappings()
  } catch (e) {
    if (e !== 'cancel') ElMessage.error('删除失败')
  }
}
</script>

<style scoped>
.toolbar {
  margin-bottom: 16px;
  display: flex;
  gap: 12px;
}
</style>

// frontend-react/src/pages/workflow-config/NodeMappings.jsx
import { useState, useEffect } from 'react'
import { Table, Button, Select, Modal, Form, Input, message } from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons'
import { workflowApi } from '@/api/workflow'

function NodeMappings() {
  const [workflows, setWorkflows] = useState([])
  const [mappings, setMappings] = useState([])
  const [selectedRouteId, setSelectedRouteId] = useState(null)
  const [loading, setLoading] = useState(false)
  const [dialogVisible, setDialogVisible] = useState(false)
  const [dialogTitle, setDialogTitle] = useState('新建映射')
  const [formData, setFormData] = useState({
    node_id: '',
    node_name: '',
    intent_schema_path: '',
    artifact_schema_path: ''
  })
  const [editingId, setEditingId] = useState(null)
  const [form] = Form.useForm()

  useEffect(() => {
    fetchWorkflows()
  }, [])

  const fetchWorkflows = async () => {
    try {
      const data = await workflowApi.getWorkflows()
      const list = Array.isArray(data) ? data : (data?.items || [])
      setWorkflows(list)
    } catch (e) {
      message.error('获取工作流列表失败')
    }
  }

  const fetchMappings = async () => {
    if (!selectedRouteId) return
    setLoading(true)
    try {
      const data = await workflowApi.getMappings(selectedRouteId)
      setMappings(data?.items || [])
    } catch (e) {
      message.error('获取映射列表失败')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (selectedRouteId) {
      fetchMappings()
    } else {
      setMappings([])
    }
  }, [selectedRouteId])

  const handleCreate = () => {
    setFormData({
      node_id: '',
      node_name: '',
      intent_schema_path: '',
      artifact_schema_path: ''
    })
    setEditingId(null)
    setDialogTitle('新建映射')
    setDialogVisible(true)
  }

  const handleEdit = (record) => {
    setFormData({ ...record })
    setEditingId(record.id)
    setDialogTitle('编辑映射')
    setDialogVisible(true)
  }

  const handleDelete = (record) => {
    Modal.confirm({
      title: '确认删除',
      content: '确认删除该映射吗？',
      okText: '确认',
      cancelText: '取消',
      onOk: async () => {
        try {
          await workflowApi.deleteMapping(record.id)
          message.success('删除成功')
          fetchMappings()
        } catch (e) {
          message.error('删除失败')
        }
      }
    })
  }

  const handleSave = async () => {
    try {
      if (editingId) {
        await workflowApi.updateMapping(editingId, formData)
        message.success('更新成功')
      } else {
        await workflowApi.createMapping(selectedRouteId, formData)
        message.success('创建成功')
      }
      setDialogVisible(false)
      fetchMappings()
    } catch (e) {
      message.error('操作失败')
    }
  }

  const columns = [
    { title: '节点ID', dataIndex: 'node_id', key: 'node_id' },
    { title: '节点名称', dataIndex: 'node_name', key: 'node_name' },
    { title: '意图表单路径', dataIndex: 'intent_schema_path', key: 'intent_schema_path', ellipsis: true },
    { title: '生成物表单路径', dataIndex: 'artifact_schema_path', key: 'artifact_schema_path', ellipsis: true },
    {
      title: '操作',
      key: 'action',
      width: 150,
      render: (_, record) => (
        <>
          <Button
            type="link"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
            style={{ color: '#5C7CFF' }}
          >
            编辑
          </Button>
          <Button
            type="link"
            danger
            icon={<DeleteOutlined />}
            onClick={() => handleDelete(record)}
          >
            删除
          </Button>
        </>
      )
    }
  ]

  return (
    <div style={{ padding: 20 }}>
      {/* Toolbar */}
      <div style={{ marginBottom: 16, display: 'flex', gap: 12 }}>
        <Select
          placeholder="选择工作流"
          value={selectedRouteId}
          onChange={(val) => setSelectedRouteId(val)}
          style={{ width: 240 }}
          options={workflows.map(w => ({ value: w.id, label: w.title || w.name }))}
        />
        <Button
          type="primary"
          icon={<PlusOutlined />}
          onClick={handleCreate}
          disabled={!selectedRouteId}
          style={{ background: '#5C7CFF', border: 'none', borderRadius: 8 }}
        >
          新建映射
        </Button>
      </div>

      {/* Table */}
      <Table
        dataSource={mappings}
        columns={columns}
        rowKey="id"
        loading={loading}
        pagination={false}
        locale={{
          emptyText: '请选择工作流查看映射'
        }}
      />

      {/* Dialog */}
      <Modal
        title={dialogTitle}
        open={dialogVisible}
        onOk={handleSave}
        onCancel={() => setDialogVisible(false)}
        okText="保存"
        cancelText="取消"
        width={600}
      >
        <Form layout="vertical" form={form}>
          <Form.Item label="节点ID">
            <Input
              value={formData.node_id}
              onChange={(e) => setFormData({ ...formData, node_id: e.target.value })}
              placeholder="node_001"
            />
          </Form.Item>
          <Form.Item label="节点名称">
            <Input
              value={formData.node_name}
              onChange={(e) => setFormData({ ...formData, node_name: e.target.value })}
              placeholder="意图澄清节点"
            />
          </Form.Item>
          <Form.Item label="意图表单Schema路径">
            <Input
              value={formData.intent_schema_path}
              onChange={(e) => setFormData({ ...formData, intent_schema_path: e.target.value })}
              placeholder="intent_forms/{route_id}/intent_schema.json"
            />
          </Form.Item>
          <Form.Item label="生成物表单Schema路径">
            <Input
              value={formData.artifact_schema_path}
              onChange={(e) => setFormData({ ...formData, artifact_schema_path: e.target.value })}
              placeholder="artifact_forms/{route_id}/artifact_schema.json"
            />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default NodeMappings
