// frontend/src/views/workflow-config/WorkflowRoutes.vue
<template>
  <div class="workflow-routes">
    <div class="toolbar">
      <el-button type="primary" @click="handleCreate">
        <el-icon><Plus /></el-icon>
        新建工作流
      </el-button>
    </div>

    <el-table :data="workflows" v-loading="loading">
      <el-table-column prop="title" label="标题" />
      <el-table-column prop="description" label="描述" show-overflow-tooltip />
      <el-table-column prop="n8n_workflow_id" label="N8N工作流ID" />
      <el-table-column prop="is_active" label="状态">
        <template #default="{ row }">
          <el-tag :type="row.is_active ? 'success' : 'info'" size="small">
            {{ row.is_active ? '激活' : '禁用' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200">
        <template #default="{ row }">
          <el-button link type="primary" @click="handleEdit(row)">编辑</el-button>
          <el-button link type="danger" @click="handleDelete(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog v-model="dialogVisible" :title="dialogTitle" width="600px">
      <el-form :model="formData" label-width="120px">
        <el-form-item label="所属环境">
          <el-select v-model="formData.environment_id" placeholder="请选择">
            <el-option
              v-for="env in environments"
              :key="env.id"
              :label="env.name"
              :value="env.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="标题">
          <el-input v-model="formData.title" />
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="formData.description" type="textarea" :rows="3" />
        </el-form-item>
        <el-form-item label="N8N工作流ID">
          <el-input v-model="formData.n8n_workflow_id" />
        </el-form-item>
        <el-form-item label="激活状态">
          <el-switch v-model="formData.is_active" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSave">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import { workflowApi } from '@/api/workflow'

const workflows = ref([])
const environments = ref([])
const loading = ref(false)
const dialogVisible = ref(false)
const dialogTitle = ref('')
const formData = ref({
  environment_id: '',
  title: '',
  description: '',
  n8n_workflow_id: '',
  is_active: true
})

onMounted(() => {
  fetchData()
})

const fetchData = async () => {
  loading.value = true
  try {
    const [wfRes, envRes] = await Promise.all([
      workflowApi.getWorkflows(),
      workflowApi.getEnvironments()
    ])
    workflows.value = wfRes.data.items
    environments.value = envRes.data
  } finally {
    loading.value = false
  }
}

const handleCreate = () => {
  formData.value = { environment_id: '', title: '', description: '', n8n_workflow_id: '', is_active: true }
  dialogTitle.value = '新建工作流'
  dialogVisible.value = true
}

const handleEdit = (row) => {
  formData.value = { ...row }
  dialogTitle.value = '编辑工作流'
  dialogVisible.value = true
}

const handleSave = async () => {
  try {
    if (formData.value.id) {
      await workflowApi.updateWorkflow(formData.value.id, formData.value)
      ElMessage.success('更新成功')
    } else {
      await workflowApi.createWorkflow(formData.value)
      ElMessage.success('创建成功')
    }
    dialogVisible.value = false
    fetchData()
  } catch (e) {
    ElMessage.error('操作失败')
  }
}

const handleDelete = async (row) => {
  try {
    await ElMessageBox.confirm('确认删除该工作流吗？', '警告', { type: 'warning' })
    await workflowApi.deleteWorkflow(row.id)
    ElMessage.success('删除成功')
    fetchData()
  } catch (e) {
    if (e !== 'cancel') ElMessage.error('删除失败')
  }
}
</script>

<style scoped>
.toolbar {
  margin-bottom: 16px;
}
</style>

// frontend-react/src/pages/workflow-config/WorkflowRoutes.jsx
import { useEffect, useState } from 'react'
import {
  Table, Button, Modal, Form, Input, InputNumber, Switch, Select,
  message, Popconfirm, Space,
} from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons'
import { workflowApi } from '@/api/workflow'

const EMPTY_FORM = {
  environment_id: undefined,
  title: '',
  description: '',
  n8n_workflow_id: '',
  is_active: true,
  sort_order: 0,
}

function WorkflowRoutes() {
  const [data, setData] = useState([])
  const [environments, setEnvironments] = useState([])
  const [loading, setLoading] = useState(false)
  const [dialogVisible, setDialogVisible] = useState(false)
  const [dialogTitle, setDialogTitle] = useState('新建工作流')
  const [formData, setFormData] = useState(EMPTY_FORM)
  const [editingId, setEditingId] = useState(null)

  const fetchData = async () => {
    setLoading(true)
    try {
      // ！api/index.js 的 response interceptor 已解包 axios response
      const list = await workflowApi.getWorkflows()
      setData(Array.isArray(list) ? list : (list?.items || []))
    } catch (e) {
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  const fetchEnvironments = async () => {
    try {
      const list = await workflowApi.getEnvironments()
      setEnvironments(Array.isArray(list) ? list : [])
    } catch (e) {
      console.error(e)
    }
  }

  useEffect(() => {
    fetchData()
    fetchEnvironments()
  }, [])

  const handleCreate = () => {
    setFormData(EMPTY_FORM)
    setEditingId(null)
    setDialogTitle('新建工作流')
    setDialogVisible(true)
  }

  const handleEdit = (record) => {
    setFormData({
      environment_id: record.environment_id,
      title: record.title || '',
      description: record.description || '',
      n8n_workflow_id: record.n8n_workflow_id || '',
      is_active: record.is_active !== false,
      sort_order: record.sort_order ?? 0,
    })
    setEditingId(record.id)
    setDialogTitle('编辑工作流')
    setDialogVisible(true)
  }

  const handleDelete = async (record) => {
    try {
      // model workflow.py:18 级联删除 node_mappings
      await workflowApi.deleteWorkflow(record.id)
      message.success('删除成功')
      fetchData()
    } catch (e) {
      message.error('删除失败')
    }
  }

  const handleSave = async () => {
    if (!formData.title.trim()) {
      message.error('请输入名称')
      return
    }
    if (!formData.environment_id) {
      message.error('请选择所属环境')
      return
    }
    try {
      if (editingId) {
        await workflowApi.updateWorkflow(editingId, formData)
        message.success('更新成功')
      } else {
        await workflowApi.createWorkflow(formData)
        message.success('创建成功')
      }
      setDialogVisible(false)
      fetchData()
    } catch (e) {
      message.error('操作失败')
    }
  }

  const columns = [
    { title: '名称', dataIndex: 'title', width: 180 },
    {
      title: '所属环境', dataIndex: 'environment_id', width: 160,
      render: (id) => environments.find(e => e.id === id)?.name || id || '—',
    },
    { title: '描述', dataIndex: 'description', ellipsis: true },
    {
      title: 'N8N Workflow ID', dataIndex: 'n8n_workflow_id', width: 200, ellipsis: true,
      render: v => v || '—',
    },
    { title: '排序', dataIndex: 'sort_order', width: 80, align: 'center' },
    {
      title: '是否激活', dataIndex: 'is_active', width: 100,
      render: v => <Switch checked={!!v} disabled />,
    },
    {
      title: '操作', width: 180, fixed: 'right',
      render: (_, record) => (
        <Space>
          <Button size="small" icon={<EditOutlined />} onClick={() => handleEdit(record)}>
            编辑
          </Button>
          <Popconfirm
            title="确认删除"
            description="删除工作流将级联删除其下所有节点映射"
            onConfirm={() => handleDelete(record)}
            okText="确认"
            cancelText="取消"
          >
            <Button size="small" danger icon={<DeleteOutlined />}>
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ]

  return (
    <div>
      <div style={{ marginBottom: 16 }}>
        <Button type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
          新增工作流
        </Button>
      </div>
      <Table
        columns={columns}
        dataSource={data}
        loading={loading}
        rowKey="id"
        scroll={{ x: 1100 }}
        style={{ background: '#fff', borderRadius: 12 }}
      />
      <Modal
        title={dialogTitle}
        open={dialogVisible}
        onOk={handleSave}
        onCancel={() => setDialogVisible(false)}
        okText="保存"
        cancelText="取消"
        width={600}
        destroyOnClose
      >
        <Form layout="vertical">
          <Form.Item label="所属环境" required>
            <Select
              value={formData.environment_id}
              onChange={v => setFormData({ ...formData, environment_id: v })}
              placeholder="选择 N8N 环境"
              options={environments.map(e => ({ value: e.id, label: e.name }))}
            />
          </Form.Item>
          <Form.Item label="名称" required>
            <Input
              value={formData.title}
              onChange={e => setFormData({ ...formData, title: e.target.value })}
              placeholder="品类运营分析"
              maxLength={200}
            />
          </Form.Item>
          <Form.Item label="描述">
            <Input.TextArea
              value={formData.description}
              onChange={e => setFormData({ ...formData, description: e.target.value })}
              placeholder="分析指定品类的销售数据，生成运营报告"
              autoSize={{ minRows: 2, maxRows: 4 }}
            />
          </Form.Item>
          <Form.Item label="N8N Workflow ID" tooltip="N8N 后台的工作流标识（webhook 路由用）">
            <Input
              value={formData.n8n_workflow_id}
              onChange={e => setFormData({ ...formData, n8n_workflow_id: e.target.value })}
              placeholder="demo-category-analysis"
            />
          </Form.Item>
          <Form.Item label="排序" tooltip="数字越小越靠前">
            <InputNumber
              value={formData.sort_order}
              onChange={v => setFormData({ ...formData, sort_order: v ?? 0 })}
              min={0}
              style={{ width: 120 }}
            />
          </Form.Item>
          <Form.Item label="是否激活">
            <Switch
              checked={formData.is_active}
              onChange={v => setFormData({ ...formData, is_active: v })}
            />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default WorkflowRoutes
