// frontend-react/src/pages/dashboard/Dashboard.jsx
import { Card, Row, Col, Button } from 'antd'
import { ReloadOutlined, ArrowUpOutlined, ArrowDownOutlined } from '@ant-design/icons'
import { useTaskStore } from '@/store/task'
import { useWorkflowStore } from '@/store/workflow'
import { useEffect, useState } from 'react'

function Dashboard() {
  const tasks = useTaskStore(s => s.tasks)
  const fetchTasks = useTaskStore(s => s.fetchTasks)
  const fetchWorkflows = useWorkflowStore(s => s.fetchWorkflows)
  const workflows = useWorkflowStore(s => s.workflows)

  const [refreshing, setRefreshing] = useState(false)

  useEffect(() => {
    fetchTasks()
    fetchWorkflows()
  }, [])

  const handleRefresh = async () => {
    setRefreshing(true)
    await Promise.all([fetchTasks(), fetchWorkflows()])
    setRefreshing(false)
  }

  const taskList = tasks || []
  const workflowList = workflows || []

  const stats = [
    { label: '工作流总数', value: workflowList.length, trend: 'up', change: '+2', color: '#5C7CFF', bg: 'rgba(92, 124, 255, 0.1)', icon: '📊' },
    { label: '今日执行', value: taskList.length, trend: 'up', change: '+12%', color: '#52C41A', bg: 'rgba(82, 196, 26, 0.1)', icon: '⚡' },
    { label: '进行中', value: taskList.filter(t => t.status === 'running').length, trend: 'down', change: '-1', color: '#FAAD14', bg: 'rgba(250, 173, 20, 0.1)', icon: '🔄' },
    { label: '已完成', value: taskList.filter(t => t.status === 'completed').length, trend: 'up', change: '+3', color: '#722ED1', bg: 'rgba(114, 46, 209, 0.1)', icon: '✅' }
  ]

  // Mock trend data
  const weekData = [65, 72, 58, 80, 75, 88, 92]
  const maxValue = Math.max(...weekData)

  return (
    <div style={{ padding: 24, background: '#F5F7FA', minHeight: '100%' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 }}>
        <div>
          <h1 style={{ margin: '0 0 4px', fontSize: '1.5rem', fontWeight: 700, color: '#1D2129' }}>
            中控仪表盘
          </h1>
          <p style={{ margin: 0, fontSize: '14px', color: '#86909C' }}>实时监控系统运行状态</p>
        </div>
        <Button
          icon={<ReloadOutlined spin={refreshing} />}
          onClick={handleRefresh}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            borderRadius: 8,
            border: '1px solid #E5E6EB',
            background: '#fff'
          }}
        >
          刷新数据
        </Button>
      </div>

      {/* Stats Grid */}
      <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
        {stats.map((stat, index) => (
          <Col span={6} key={index}>
            <Card
              style={{
                borderRadius: 14,
                background: '#fff',
                border: '1px solid #E5E6EB',
                transition: 'all 0.2s'
              }}
              styles={{ body: { padding: 20 } }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                <div style={{
                  width: 48,
                  height: 48,
                  borderRadius: 12,
                  background: stat.bg,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: 20
                }}>
                  {stat.icon}
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: '1.75rem', fontWeight: 700, color: stat.color, lineHeight: 1.2 }}>
                    {stat.value}
                  </div>
                  <div style={{ fontSize: '13px', color: '#86909C', marginTop: 4 }}>
                    {stat.label}
                  </div>
                </div>
                <div style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 2,
                  fontSize: '12px',
                  fontWeight: 600,
                  padding: '4px 8px',
                  borderRadius: 6,
                  color: stat.trend === 'up' ? '#52C41A' : '#FF4D4F',
                  background: stat.trend === 'up' ? 'rgba(82, 196, 26, 0.1)' : 'rgba(255, 77, 79, 0.1)'
                }}>
                  {stat.trend === 'up' ? <ArrowUpOutlined /> : <ArrowDownOutlined />}
                  {stat.change}
                </div>
              </div>
            </Card>
          </Col>
        ))}
      </Row>

      {/* Content Grid */}
      <Row gutter={[16, 16]}>
        {/* Chart Card */}
        <Col span={16}>
          <Card
            style={{ borderRadius: 14, border: '1px solid #E5E6EB' }}
            title={<span style={{ fontWeight: 600, fontSize: '15px', color: '#1D2129' }}>执行趋势</span>}
            extra={
              <div style={{ display: 'flex', gap: 8 }}>
                <span style={{ padding: '4px 12px', fontSize: '12px', borderRadius: 6, background: '#F0F1FF', color: '#5C7CFF', fontWeight: 500 }}>本周</span>
                <span style={{ padding: '4px 12px', fontSize: '12px', borderRadius: 6, color: '#86909C' }}>本月</span>
              </div>
            }
            styles={{ header: { padding: '16px 20px', borderBottom: '1px solid #E5E6EB' }, body: { padding: '20px' } }}
          >
            <div style={{ height: 200, display: 'flex', alignItems: 'flex-end', padding: '20px 0' }}>
              <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', width: '100%', height: '100%', gap: 12 }}>
                {weekData.map((value, index) => (
                  <div key={index} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
                    <div
                      style={{
                        width: '100%',
                        height: `${(value / maxValue) * 100}%`,
                        background: 'linear-gradient(180deg, #5C7CFF 0%, #7B91FF 100%)',
                        borderRadius: '8px 8px 0 0',
                        animation: 'growUp 0.6s ease-out forwards',
                        animationDelay: `${index * 0.1}s`
                      }}
                    />
                    <span style={{ fontSize: '12px', color: '#86909C' }}>周{index + 1}</span>
                  </div>
                ))}
              </div>
            </div>
            <style>{`
              @keyframes growUp {
                from { transform: scaleY(0); transform-origin: bottom; }
                to { transform: scaleY(1); transform-origin: bottom; }
              }
            `}</style>
          </Card>
        </Col>

        {/* Activity Card */}
        <Col span={8}>
          <Card
            style={{ borderRadius: 14, border: '1px solid #E5E6EB', height: '100%' }}
            title={<span style={{ fontWeight: 600, fontSize: '15px', color: '#1D2129' }}>最近活动</span>}
            styles={{ header: { padding: '16px 20px', borderBottom: '1px solid #E5E6EB' }, body: { padding: '16px 20px' } }}
          >
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {taskList.slice(0, 5).map((task, index) => (
                <div key={index} style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                  <div style={{
                    width: 8,
                    height: 8,
                    borderRadius: '50%',
                    background: task.status === 'completed' ? '#52C41A' : task.status === 'running' ? '#5C7CFF' : '#86909C',
                    marginTop: 6,
                    flexShrink: 0
                  }} />
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: '14px', fontWeight: 500, color: '#1D2129' }}>
                      {task.name || '未命名任务'}
                    </div>
                    <div style={{ fontSize: '12px', color: '#86909C', marginTop: 2 }}>
                      {task.status === 'completed' ? '已完成' : task.status === 'running' ? '进行中' : '待执行'}
                    </div>
                  </div>
                </div>
              ))}
              {taskList.length === 0 && (
                <div style={{ textAlign: 'center', color: '#86909C', padding: 20 }}>
                  暂无活动记录
                </div>
              )}
            </div>
          </Card>
        </Col>
      </Row>
    </div>
  )
}

export default Dashboard

// frontend/src/views/dashboard/Dashboard.vue
<template>
  <div class="dashboard">
    <div class="header">
      <div class="header-content">
        <h1>中控仪表盘</h1>
        <p>实时监控系统运行状态</p>
      </div>
      <div class="header-actions">
        <el-button class="refresh-btn" @click="refreshData">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M23 4v6h-6M1 20v-6h6"/>
            <path d="M3.51 9a9 9 0 0114.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0020.49 15"/>
          </svg>
          刷新数据
        </el-button>
      </div>
    </div>

    <div class="stats-grid">
      <div
        v-for="(stat, index) in stats"
        :key="index"
        class="stat-card"
        :style="{ '--delay': `${index * 0.1}s` }"
      >
        <div class="stat-icon" :style="{ background: stat.iconBg }">
          <component :is="stat.icon" />
        </div>
        <div class="stat-content">
          <div class="stat-value">{{ stat.value }}</div>
          <div class="stat-label">{{ stat.label }}</div>
        </div>
        <div class="stat-trend" :class="stat.trend">
          <svg v-if="stat.trend === 'up'" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M18 15l-6-6-6 6"/>
          </svg>
          <svg v-else-if="stat.trend === 'down'" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M6 9l6 6 6-6"/>
          </svg>
          <span>{{ stat.change }}</span>
        </div>
      </div>
    </div>

    <div class="content-grid">
      <el-card class="chart-card">
        <template #header>
          <div class="card-header">
            <span class="card-title">执行趋势</span>
            <div class="card-tabs">
              <span class="tab active">本周</span>
              <span class="tab">本月</span>
            </div>
          </div>
        </template>
        <div class="chart-placeholder">
          <div class="chart-bars">
            <div v-for="i in 7" :key="i" class="bar" :style="{ height: `${Math.random() * 60 + 40}%` }"></div>
          </div>
        </div>
      </el-card>

      <el-card class="activity-card">
        <template #header>
          <div class="card-header">
            <span class="card-title">最近活动</span>
          </div>
        </template>
        <div class="activity-list">
          <div v-for="i in 5" :key="i" class="activity-item">
            <div class="activity-dot"></div>
            <div class="activity-content">
              <div class="activity-title">品类运营分析</div>
              <div class="activity-desc">已完成 · 2分钟前</div>
            </div>
          </div>
        </div>
      </el-card>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const stats = ref([
  { label: '工作流总数', value: '12', trend: 'up', change: '+2', iconBg: 'rgba(102, 126, 234, 0.1)' },
  { label: '今日执行', value: '156', trend: 'up', change: '+12%', iconBg: 'rgba(16, 185, 129, 0.1)' },
  { label: '成功率', value: '98.7%', trend: 'down', change: '-0.3%', iconBg: 'rgba(245, 158, 11, 0.1)' },
  { label: 'N8N环境', value: '3', trend: 'up', change: '+1', iconBg: 'rgba(118, 75, 162, 0.1)' }
])

const refreshData = () => {
  console.log('Refresh data')
}
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');

.dashboard {
  padding: 24px;
  background: #f8f9fb;
  min-height: 100%;
  font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, sans-serif;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 24px;
}

.header-content h1 {
  margin: 0 0 4px 0;
  font-size: 1.5rem;
  font-weight: 700;
  color: #1a1a2e;
}

.header-content p {
  margin: 0;
  font-size: 0.85rem;
  color: #94a3b8;
}

.refresh-btn {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 16px;
  border-radius: 8px;
  border: 1px solid rgba(0, 0, 0, 0.08);
  background: #fff;
  color: #64748b;
  font-size: 0.85rem;
  transition: all 0.2s;
}

.refresh-btn:hover {
  border-color: #667eea;
  color: #667eea;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
  margin-bottom: 24px;
}

.stat-card {
  background: #fff;
  border-radius: 16px;
  padding: 20px;
  display: flex;
  align-items: center;
  gap: 16px;
  border: 1px solid rgba(0, 0, 0, 0.04);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.02);
  animation: slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1) both;
  animation-delay: var(--delay);
  transition: all 0.2s;
}

.stat-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.08);
}

@keyframes slideUp {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.stat-icon {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #667eea;
}

.stat-content {
  flex: 1;
}

.stat-value {
  font-size: 1.5rem;
  font-weight: 700;
  color: #1a1a2e;
  line-height: 1.2;
}

.stat-label {
  font-size: 0.8rem;
  color: #94a3b8;
  margin-top: 2px;
}

.stat-trend {
  display: flex;
  align-items: center;
  gap: 2px;
  font-size: 0.75rem;
  font-weight: 600;
  padding: 4px 8px;
  border-radius: 6px;
}

.stat-trend.up {
  color: #10b981;
  background: rgba(16, 185, 129, 0.1);
}

.stat-trend.down {
  color: #ef4444;
  background: rgba(239, 68, 68, 0.1);
}

.content-grid {
  display: grid;
  grid-template-columns: 2fr 1fr;
  gap: 16px;
}

.chart-card, .activity-card {
  border-radius: 16px;
  border: 1px solid rgba(0, 0, 0, 0.04);
}

:deep(.el-card__header) {
  padding: 16px 20px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.04);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.card-title {
  font-size: 0.95rem;
  font-weight: 600;
  color: #1a1a2e;
}

.card-tabs {
  display: flex;
  gap: 8px;
}

.tab {
  padding: 4px 12px;
  font-size: 0.8rem;
  color: #94a3b8;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s;
}

.tab:hover {
  color: #667eea;
}

.tab.active {
  color: #667eea;
  background: rgba(102, 126, 234, 0.1);
}

.chart-placeholder {
  height: 200px;
  display: flex;
  align-items: flex-end;
  padding: 20px 0;
}

.chart-bars {
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  width: 100%;
  height: 100%;
  gap: 12px;
}

.bar {
  flex: 1;
  background: linear-gradient(180deg, #667eea 0%, #764ba2 100%);
  border-radius: 8px 8px 0 0;
  animation: growUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) both;
}

@keyframes growUp {
  from {
    transform: scaleY(0);
    transform-origin: bottom;
  }
  to {
    transform: scaleY(1);
    transform-origin: bottom;
  }
}

.activity-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.activity-item {
  display: flex;
  align-items: flex-start;
  gap: 12px;
}

.activity-dot {
  width: 8px;
  height: 8px;
  background: #667eea;
  border-radius: 50%;
  margin-top: 6px;
}

.activity-content {
  flex: 1;
}

.activity-title {
  font-size: 0.9rem;
  font-weight: 500;
  color: #1a1a2e;
}

.activity-desc {
  font-size: 0.8rem;
  color: #94a3b8;
  margin-top: 2px;
}
</style>
