// frontend-react/src/pages/ai-assistant/WorkflowSidebar.jsx
import { useState } from 'react'
import { Checkbox, Button, Popconfirm } from 'antd'
import { DeleteOutlined, PlusOutlined, ClockCircleOutlined } from '@ant-design/icons'
import { useTaskStore } from '@/store/task'
import { useChatStore } from '@/store/chat'

const statusMap = {
  pending: { text: '待执行', color: '#86909C', bg: '#F5F7FA' },
  running: { text: '执行中', color: '#5C7CFF', bg: '#F0F1FF' },
  completed: { text: '已完成', color: '#52C41A', bg: '#F6FFED' },
  failed: { text: '失败', color: '#FF4D4F', bg: '#FFF2F0' }
}

function formatTime(timestamp) {
  if (!timestamp) return ''
  const date = new Date(timestamp.endsWith('Z') ? timestamp : timestamp + 'Z')
  const now = new Date()
  const diff = now - date
  if (diff < 60000) return '刚刚'
  if (diff < 3600000) return `${Math.floor(diff / 60000)}分钟前`
  if (diff < 86400000) return `${Math.floor(diff / 3600000)}小时前`
  return date.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

function formatFullTime(timestamp) {
  if (!timestamp) return ''
  const date = new Date(timestamp.endsWith('Z') ? timestamp : timestamp + 'Z')
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  const hours = String(date.getHours()).padStart(2, '0')
  const minutes = String(date.getMinutes()).padStart(2, '0')
  return `${year}-${month}-${day} ${hours}:${minutes}`
}

function WorkflowSidebar() {
  const tasks = useTaskStore(s => s.tasks)
  const currentTask = useTaskStore(s => s.currentTask)
  const setCurrentNode = useTaskStore(s => s.setCurrentNode)
  const clearCurrentTask = useTaskStore(s => s.clearCurrentTask)
  const setSelectedWorkflow = useChatStore(s => s.setSelectedWorkflow)
  const deleteTask = useTaskStore(s => s.deleteTask)
  const deleteTasks = useTaskStore(s => s.deleteTasks)

  const [selectedRowKeys, setSelectedRowKeys] = useState([])
  const [isSelectMode, setIsSelectMode] = useState(false)

  const handleSelectTask = async (task) => {
    if (isSelectMode) return
    setSelectedWorkflow(null)
    const detail = await useTaskStore.getState().fetchTask(task.id)

    let targetNodeId = null
    if (task.status === 'running' && task.current_node_id) {
      // 执行中状态 → 跳转到正在执行的节点，并启动轮询
      targetNodeId = task.current_node_id
      useTaskStore.getState().startPolling(task.id, targetNodeId)
    } else if (detail.nodes?.length > 0) {
      // 其他状态 → 跳转到第一个节点
      targetNodeId = detail.nodes[0].node_id
    }

    if (targetNodeId) {
      useTaskStore.getState().setCurrentNode(targetNodeId)
    }
  }

  const handleNewConversation = () => {
    clearCurrentTask()
    setSelectedWorkflow(null)
    setIsSelectMode(false)
    setSelectedRowKeys([])
  }

  const handleDelete = async (taskId, e) => {
    e.stopPropagation()
    await deleteTask(taskId)
    setSelectedRowKeys(prev => prev.filter(id => id !== taskId))
  }

  const handleBatchDelete = async () => {
    await deleteTasks(selectedRowKeys)
    setSelectedRowKeys([])
    setIsSelectMode(false)
  }

  const handleSelectAll = (checked) => {
    if (checked) {
      setSelectedRowKeys(tasks.map(t => t.id))
    } else {
      setSelectedRowKeys([])
    }
  }

  const rowSelection = {
    selectedRowKeys,
    onChange: setSelectedRowKeys
  }

  return (
    <div style={{
      background: '#FFFFFF',
      borderRadius: 14,
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      border: '1px solid #E5E6EB',
      overflow: 'hidden'
    }}>
      {/* Header */}
      <div style={{
        padding: '18px 20px',
        borderBottom: '1px solid #E5E6EB',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center'
      }}>
        <span style={{
          fontSize: '15px',
          fontWeight: 600,
          color: '#1D2129'
        }}>
          工作流实例
        </span>
        {tasks.length > 0 && (
          <Button
            type="text"
            size="small"
            onClick={() => {
              setIsSelectMode(!isSelectMode)
              if (isSelectMode) {
                setSelectedRowKeys([])
              }
            }}
            style={{ color: isSelectMode ? '#5C7CFF' : '#86909C' }}
          >
            {isSelectMode ? '取消' : '选择'}
          </Button>
        )}
      </div>

      {/* Batch Actions */}
      {isSelectMode && selectedRowKeys.length > 0 && (
        <div style={{
          padding: '8px 12px',
          background: '#F0F1FF',
          borderBottom: '1px solid #E5E6EB',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <Checkbox
            onChange={(e) => handleSelectAll(e.target.checked)}
            checked={selectedRowKeys.length === tasks.length && tasks.length > 0}
            indeterminate={selectedRowKeys.length > 0 && selectedRowKeys.length < tasks.length}
          >
            <span style={{ fontSize: '12px', color: '#5C7CFF' }}>
              已选 {selectedRowKeys.length} 项
            </span>
          </Checkbox>
          <Button
            type="text"
            danger
            size="small"
            icon={<DeleteOutlined />}
            onClick={handleBatchDelete}
          >
            批量删除
          </Button>
        </div>
      )}

      {/* Task List */}
      <div style={{ flex: 1, overflow: 'auto', padding: '8px 12px' }}>
        {/* "新对话" 虚拟条目 */}
        <div
          onClick={handleNewConversation}
          style={{
            display: 'flex',
            gap: 12,
            padding: '12px',
            borderRadius: 10,
            marginBottom: 6,
            cursor: 'pointer',
            background: !currentTask ? '#F0F1FF' : 'transparent',
            border: !currentTask ? '1px solid #7B91FF' : '1px solid transparent',
            transition: 'all 0.15s ease'
          }}
        >
          <div style={{
            width: 32,
            height: 32,
            borderRadius: 6,
            background: !currentTask ? '#E0E7FF' : 'linear-gradient(135deg, rgba(92, 124, 255, 0.15) 0%, rgba(123, 145, 255, 0.15) 100%)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: !currentTask ? '#5C7CFF' : '#667eea',
            flexShrink: 0
          }}>
            <PlusOutlined />
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontWeight: 500, fontSize: '13px', color: !currentTask ? '#5C7CFF' : '#374151', marginBottom: 6 }}>
              新对话
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '11px' }}>
              <span style={{ color: '#8b5cf6', background: 'rgba(139, 92, 246, 0.1)', padding: '2px 8px', borderRadius: 10 }}>
                草稿
              </span>
              <span style={{ color: '#9ca3af' }}>未开始执行</span>
            </div>
          </div>
        </div>

        {/* 已存在的任务实例 */}
        {tasks.map((task) => {
          const status = statusMap[task.status] || statusMap.pending
          const isActive = currentTask?.id === task.id
          const isSelected = selectedRowKeys.includes(task.id)

          return (
            <div
              key={task.id}
              onClick={() => handleSelectTask(task)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                padding: '12px',
                borderRadius: 10,
                marginBottom: 6,
                cursor: 'pointer',
                background: isActive ? '#F0F1FF' : isSelected ? '#E0E7FF' : 'transparent',
                border: isActive ? '1px solid #7B91FF' : isSelected ? '1px solid #5C7CFF' : '1px solid transparent',
                transition: 'all 0.15s ease'
              }}
            >
              {isSelectMode && (
                <Checkbox
                  checked={isSelected}
                  onClick={(e) => e.stopPropagation()}
                  onChange={(e) => {
                    if (e.target.checked) {
                      setSelectedRowKeys([...selectedRowKeys, task.id])
                    } else {
                      setSelectedRowKeys(selectedRowKeys.filter(id => id !== task.id))
                    }
                  }}
                />
              )}
              <div style={{
                width: 32,
                height: 32,
                borderRadius: 6,
                background: isActive ? '#E0E7FF' : '#f1f5f9',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: isActive ? '#5C7CFF' : '#64748b',
                flexShrink: 0
              }}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="3" y="3" width="18" height="18" rx="2"/>
                  <path d="M9 12l2 2 4-4"/>
                </svg>
              </div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontWeight: 500, fontSize: '13px', color: isActive ? '#5C7CFF' : '#374151', marginBottom: 8 }}>
                  {task.name || '未命名任务'}
                </div>

                {/* Node Progress Indicator */}
                {task.node_executions?.length > 0 && (
                  <div style={{ display: 'flex', alignItems: 'center', marginBottom: 6 }}>
                    {task.node_executions.map((node, index) => (
                      <div key={node.node_id} style={{ display: 'flex', alignItems: 'center' }}>
                        <div style={{
                          width: 8,
                          height: 8,
                          borderRadius: '50%',
                          background: node.status === 'completed' ? '#52C41A' : node.status === 'running' ? '#8b5cf6' : '#d1d5db',
                          flexShrink: 0,
                          animation: node.status === 'running' ? 'pulse 1.5s ease-in-out infinite' : 'none',
                          boxShadow: node.status === 'running' ? '0 0 0 0 rgba(139, 92, 246, 0.4)' : 'none'
                        }} />
                        {index < task.node_executions.length - 1 && (
                          <div style={{
                            width: 16,
                            height: 2,
                            background: node.status === 'completed' ? '#52C41A' : '#d1d5db',
                            margin: '0 2px'
                          }} />
                        )}
                      </div>
                    ))}
                  </div>
                )}

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{
                    fontSize: '11px',
                    color: status.color,
                    background: status.bg,
                    padding: '2px 8px',
                    borderRadius: 10
                  }}>
                    {status.text}
                  </span>
                  {task.node_executions?.[0] && (
                    <span style={{ fontSize: '11px', color: '#9ca3af', display: 'flex', alignItems: 'center', gap: 4 }}>
                      <ClockCircleOutlined style={{ fontSize: 10 }} />
                      {formatFullTime(task.node_executions[0].started_at)}
                      {task.node_executions[0].completed_at && (
                        <> → {formatFullTime(task.node_executions[0].completed_at)}</>
                      )}
                    </span>
                  )}
                </div>
              </div>
              {!isSelectMode && (
                <Popconfirm
                  title="确定删除此任务？"
                  onConfirm={(e) => handleDelete(task.id, e)}
                  onCancel={(e) => e.stopPropagation()}
                  okText="确定"
                  cancelText="取消"
                  placement="left"
                >
                  <Button
                    type="text"
                    size="small"
                    danger
                    icon={<DeleteOutlined />}
                    onClick={(e) => e.stopPropagation()}
                    style={{ opacity: 0.6 }}
                  />
                </Popconfirm>
              )}
            </div>
          )
        })}

        {tasks.length === 0 && (
          <div style={{ textAlign: 'center', padding: '32px 16px', color: '#9ca3af', fontSize: '13px' }}>
            暂无任务实例
          </div>
        )}
      </div>
      <style>{`
        @keyframes pulse {
          0% { box-shadow: 0 0 0 0 rgba(139, 92, 246, 0.4); }
          70% { box-shadow: 0 0 0 6px rgba(139, 92, 246, 0); }
          100% { box-shadow: 0 0 0 0 rgba(139, 92, 246, 0); }
        }
      `}</style>
    </div>
  )
}

export default WorkflowSidebar

// frontend/src/views/ai-assistant/WorkflowSidebar.vue
<template>
  <div class="workflow-sidebar">
    <!-- Header -->
    <div class="sidebar-header">
      <h3 class="sidebar-title">工作流实例</h3>
    </div>

    <!-- Task List -->
    <div class="task-list">
      <!-- "新对话" 虚拟实例 -->
      <div
        class="task-item"
        :class="{ active: !taskStore.currentTask }"
        @click="selectNewConversation"
      >
        <div class="task-icon new-conversation">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M12 5v14M5 12h14"/>
          </svg>
        </div>
        <div class="task-content">
          <div class="task-name">新对话</div>
          <div class="task-meta">
            <span class="task-status draft">草稿</span>
            <span class="task-time">未开始执行</span>
          </div>
        </div>
      </div>

      <!-- 已存在的任务实例 -->
      <div
        v-for="task in taskStore.tasks"
        :key="task.id"
        class="task-item"
        :class="{ active: taskStore.currentTask?.id === task.id }"
        @click="selectTask(task)"
      >
        <div class="task-icon">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <rect x="3" y="3" width="18" height="18" rx="2"/>
            <path d="M9 12l2 2 4-4"/>
          </svg>
        </div>
        <div class="task-content">
          <div class="task-name">{{ task.name || '未命名任务' }}</div>

          <!-- Node Progress Indicator -->
          <div class="node-progress" v-if="task.node_executions?.length">
            <template v-for="(node, index) in task.node_executions" :key="node.node_id">
              <div
                class="node-dot"
                :class="{
                  completed: node.status === 'completed',
                  active: node.status === 'executing' || node.node_id === taskStore.currentNodeId,
                  pending: node.status === 'pending'
                }"
              ></div>
              <div
                v-if="index < task.node_executions.length - 1"
                class="node-line"
                :class="{ completed: node.status === 'completed' }"
              ></div>
            </template>
          </div>

          <div class="task-meta">
            <span class="task-status" :class="task.status">
              {{ statusText(task.status) }}
            </span>
            <span class="task-time">{{ formatTime(task.updated_at) }}</span>
          </div>
        </div>
      </div>

      <div v-if="taskStore.tasks.length === 0" class="empty-state">
        暂无任务实例
      </div>
    </div>
  </div>
</template>

<script setup>
import { useTaskStore } from '@/store/task'

const taskStore = useTaskStore()

const selectNewConversation = () => {
  taskStore.clearCurrentTask()
}

const selectTask = async (task) => {
  await taskStore.fetchTask(task.id)
}

const statusText = (status) => {
  const map = {
    pending: '待执行',
    executing: '执行中',
    completed: '已完成',
    failed: '失败'
  }
  return map[status] || status
}

const formatTime = (timestamp) => {
  if (!timestamp) return ''
  // Parse as UTC by appending 'Z' if not already present
  const dateStr = timestamp.endsWith('Z') ? timestamp : timestamp + 'Z'
  const date = new Date(dateStr)
  const now = new Date()
  const diff = now - date

  if (diff < 60000) return '刚刚'
  if (diff < 3600000) return `${Math.floor(diff / 60000)}分钟前`
  if (diff < 86400000) return `${Math.floor(diff / 3600000)}小时前`

  return date.toLocaleDateString('zh-CN', {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}
</script>

<style scoped>
.workflow-sidebar {
  width: 260px;
  flex-shrink: 0;
  background: #fff;
  border-right: 1px solid #e5e7eb;
  display: flex;
  flex-direction: column;
  height: 100%;
}

.sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px;
  border-bottom: 1px solid #f1f1f1;
}

.sidebar-title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: #1f2937;
}

.task-list {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
}

.task-item {
  display: flex;
  gap: 12px;
  padding: 12px;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
  margin-bottom: 4px;
}

.task-item:hover {
  background: #f9fafb;
}

.task-item.active {
  background: #f3f4ff;
}

.task-icon {
  width: 32px;
  height: 32px;
  border-radius: 6px;
  background: #f1f5f9;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #64748b;
  flex-shrink: 0;
}

.task-icon.new-conversation {
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.15) 0%, rgba(118, 75, 162, 0.15) 100%);
  color: #667eea;
}

.task-item.active .task-icon {
  background: #e0e7ff;
  color: #6366f1;
}

.task-content {
  flex: 1;
  min-width: 0;
}

.task-name {
  font-size: 13px;
  font-weight: 500;
  color: #374151;
  margin-bottom: 6px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.node-progress {
  display: flex;
  align-items: center;
  margin-bottom: 6px;
}

.node-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #d1d5db;
  flex-shrink: 0;
}

.node-dot.completed {
  background: #10b981;
}

.node-dot.active {
  background: #8b5cf6;
  animation: pulse 1.5s infinite;
}

@keyframes pulse {
  0%, 100% {
    box-shadow: 0 0 0 0 rgba(139, 92, 246, 0.4);
  }
  50% {
    box-shadow: 0 0 0 6px rgba(139, 92, 246, 0);
  }
}

.node-line {
  width: 16px;
  height: 2px;
  background: #d1d5db;
  margin: 0 2px;
}

.node-line.completed {
  background: #10b981;
}

.task-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 11px;
}

.task-status {
  color: #9ca3af;
}

.task-status.executing,
.task-status.draft {
  color: #8b5cf6;
}

.task-status.completed {
  color: #10b981;
}

.task-status.failed {
  color: #ef4444;
}

.task-time {
  color: #9ca3af;
}

.empty-state {
  text-align: center;
  padding: 32px 16px;
  color: #9ca3af;
  font-size: 13px;
}

.create-form {
  padding: 8px 0;
}

.form-item {
  margin-bottom: 16px;
}

.form-item label {
  display: block;
  margin-bottom: 8px;
  font-size: 13px;
  color: #374151;
}
</style>
